version: "2"
services:
  goof:
    build: .
    container_name: goof
    environment:
      - DOCKER=1
    ports:
      - "3001:3001"
      - "9229:9229"
    links:
      - goof-mongo
    depends_on:
      - goof-mongo
  goof-mongo:
    container_name: goof-mongo
    image: mongo:3
    ports:
      - "27018:27017"
  goof-mysql:
    container_name: goof-mysql
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: acme
    ports:
      - "3307:3306"